#!/bin/bash

_goenv() {
    local cur=${COMP_WORDS[COMP_CWORD]}
    COMPREPLY=( $(compgen -W "help install list use" -- $cur) )

    if [[ $COMP_CWORD -eq 2 ]] ; then
        case ${COMP_WORDS[1]} in
            use)
                versions=`ls $HOME/.goenv/root`
                COMPREPLY=( $(compgen -W "$versions" -- $cur) )
                ;;
            help)
                COMPREPLY=( $(compgen -W "install list use" -- $cur) )
                ;;
        esac
    fi
}

complete -F _goenv goenv
